BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Users" (
	"id"	INTEGER,
	"email"	VARCHAR(255) UNIQUE,
	"password"	VARCHAR(255),
	"firstName"	VARCHAR(255),
	"lastName"	VARCHAR(255),
	"phone"	VARCHAR(255),
	"isVerified"	TINYINT(1),
	"isAdmin"	TINYINT(1),
	"isDeleted"	TINYINT(1),
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Orders" (
	"id"	INTEGER,
	"status"	VARCHAR(255),
	"isDelivery"	TINYINT(1),
	"country"	VARCHAR(255),
	"city"	VARCHAR(255),
	"street"	VARCHAR(255),
	"number"	INTEGER,
	"comment"	VARCHAR(255),
	"isDeleted"	TINYINT(1),
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	"UserId"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("UserId") REFERENCES "Users"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Products" (
	"id"	INTEGER,
	"name"	VARCHAR(255),
	"description"	VARCHAR(255),
	"filePath"	VARCHAR(255),
	"price"	DOUBLE PRECISION,
	"isDeleted"	TINYINT(1),
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Colors" (
	"id"	INTEGER,
	"name"	VARCHAR(255),
	"hex"	VARCHAR(255),
	"isDeleted"	TINYINT(1),
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CartItems" (
	"id"	INTEGER,
	"quantity"	INTEGER,
	"isDeleted"	TINYINT(1),
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	"OrderId"	INTEGER,
	"UserId"	INTEGER,
	"ProductId"	INTEGER,
	"ColorId"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("ColorId") REFERENCES "Colors"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY("ProductId") REFERENCES "Products"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY("OrderId") REFERENCES "Orders"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY("UserId") REFERENCES "Users"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Tags" (
	"id"	INTEGER,
	"name"	VARCHAR(255),
	"relevance"	INTEGER,
	"isDeleted"	TINYINT(1),
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ProductTags" (
	"ProductId"	INTEGER NOT NULL,
	"TagId"	INTEGER NOT NULL,
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	PRIMARY KEY("ProductId","TagId"),
	UNIQUE("ProductId","TagId"),
	FOREIGN KEY("ProductId") REFERENCES "Products"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("TagId") REFERENCES "Tags"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
COMMIT;
